public class ConstantsCl {
    /* Application Status */
    public static final String APPLICATION_STATUS_NEW_ENTERED = 'NEW - ENTERED';
    public static final String APPLICATION_STATUS_BAQ_SUBMITTED = 'BAQ Submitted';
    public static final String APPLICATION_STATUS_UNDERWRITING = 'Underwriting';
    public static final String APPLICATION_STATUS_GUIDANCE = 'Guidance';
    public static final String APPLICATION_STATUS_SUBMITTEDL_FOR_APPROVAL = 'Submitted for Approval';
    public static final String APPLICATION_STATUS_APPROVED = 'Approved';
    public static final String APPLICATION_STATUS_BAQ_RESUBMITTED = 'BAQ Resubmitted';
    public static final String APPLICATION_STATUS_FINAL_OFFER_INITIATED = 'Final Offer Initiated';
    public static final String APPLICATION_STATUS_FINAL_OFFER_SUBMITTED = 'Final Offer Submitted';
    
    /* Opportunity Status */
    public static final String OPPORTUNITY_STATUS_FINAL_OFFER_SUBMITTED = 'Final Offer Submitted';    
    
    /* BAQ Status */
    public static final String BAQ_STATUS_SUBMITTED = 'BAQ Submitted';
    public static final String BAQ_STATUS_GUIDANCE = 'Guidance';
    public static final String BAQ_STATUS_APPROVED = 'Approved';
    
    /* Product Types */
    public static final String LOAN_PRODUCT_TYPE = 'LOAN';
    
    
    /* Loan Types */
    public static final String REPAYABLE_LOAN = 'Repayable';
    public static final String FORGIVABLE_LOAN = 'Forgivable';
    public static final String GROWTH_LOAN = 'Growth Loan';
    public static final String ACQUISITION_LOAN = 'Acquisition Loan';
    public static final String BACKEND_TA = 'Backend TA';
    public static final String RETENTION_LOAN = 'Retention Loan';
    public static final String REFINANCE_LOAN = 'Refinance Loan';
    public static final String LINE_OF_CREDIT = 'Line of Credit';
    public static final String NNA_Loan = 'NNA Loan';
    public static final String OTHER_LOAN = 'Other Loan';
    
    
    /* Message Strings */
    public static final String APPLICATION_CREATION_SUCCESS_MSG = 'SUCCESS! Application has been created.';
    public static final String APPLICATION_CREATION_MISSING_FIELDS_MSG = 'Unable to create an application! Opportunity details are missing';
    
    
    /* Loan Payment Frequency */
    public static final String LOAN_PAYMENT_FREQUENCY_SEMI_MONTHLY = 'Semi-Monthly';
    public static final String LOAN_PAYMENT_FREQUENCY_MONTHLY = 'Monthly';
    
    /* APS Types */
    public static final String APS_RECURRING_TYPE = 'RECURRING';
    public static final String APS_ONE_TIME_TYPE = 'ONE TIME';    
    
}